# right_format = '$time'

[custom.http_proxy]
command = 'echo $http_proxy'
when = 'test -n "$http_proxy"'
style = 'bold blue'
format = '[ï‡˜ $output]($style) '

# [time]
# disabled = false
# style = "italic dimmed white"
# format = '[$time]($style) '
# # 2021-07-23 15:30:00
# time_format = '%Y-%m-%d %H:%M:%S'

[container]
disabled = true
